name: golub
description: Messenger

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: 12.1.0
  flutter_svg: 2.0.9
  intl: 0.18.1
  freezed: 2.4.5
  freezed_annotation: 2.4.1
  flutter_bloc: 8.1.3
  url_launcher: 6.2.1
  dio: 5.3.4
  flutter_dotenv: 5.1.0
  injectable: 2.3.2
  get_it: 7.6.4
  slang: 3.28.0
  slang_flutter: 3.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  intl_utils: 2.8.5
  build_runner: 2.4.6
  injectable_generator: 2.4.1
  slang_build_runner: 3.28.0
  flutter_launcher_icons: 0.13.1

flutter:
  uses-material-design: true

  assets:
   - assets/icons/
   - assets/logo/
   - assets/images/

  fonts:
   - family: Ubuntu
     fonts:
       - asset: assets/fonts/ubuntu/ubuntu-regular.ttf
       - asset: assets/fonts/ubuntu/ubuntu-medium.ttf
         weight: 500
   - family: Roboto
     fonts:
       - asset: assets/fonts/roboto/roboto-regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  remove_alpha_ios: true